-- Update users table
ALTER TABLE users
ADD COLUMN IF NOT EXISTS session_token VARCHAR(255),
ADD COLUMN IF NOT EXISTS token_expiry DATETIME,
ADD COLUMN IF NOT EXISTS google_id VARCHAR(255),
MODIFY COLUMN id INT AUTO_INCREMENT,
MODIFY COLUMN userName VARCHAR(255) NOT NULL,
MODIFY COLUMN userEmail VARCHAR(255) NOT NULL,
MODIFY COLUMN userPass VARCHAR(255) NOT NULL,
ADD UNIQUE INDEX idx_user_email (userEmail),
ADD INDEX idx_session_token (session_token),
ADD INDEX idx_google_id (google_id);

-- Update tasks table
ALTER TABLE tasks
MODIFY COLUMN id INT AUTO_INCREMENT,
MODIFY COLUMN user_id INT NOT NULL,
MODIFY COLUMN title VARCHAR(255) NOT NULL,
MODIFY COLUMN list_type VARCHAR(50) NOT NULL,
MODIFY COLUMN priority_tag VARCHAR(50),
MODIFY COLUMN notes TEXT,
MODIFY COLUMN completed BOOLEAN DEFAULT FALSE,
MODIFY COLUMN archived BOOLEAN DEFAULT FALSE,
MODIFY COLUMN pinned BOOLEAN DEFAULT FALSE,
MODIFY COLUMN reminder_date DATE,
MODIFY COLUMN reminder_time TIME,
MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD INDEX idx_user_tasks (user_id),
ADD INDEX idx_list_type (list_type),
ADD INDEX idx_archived (archived),
ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- Update subtasks table
ALTER TABLE subtasks
MODIFY COLUMN id INT AUTO_INCREMENT,
MODIFY COLUMN task_id INT NOT NULL,
MODIFY COLUMN title VARCHAR(255) NOT NULL,
MODIFY COLUMN completed BOOLEAN DEFAULT FALSE,
MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD INDEX idx_task_subtasks (task_id),
ADD FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE;

-- Update diary_entries table
ALTER TABLE diary_entries
MODIFY COLUMN id INT AUTO_INCREMENT,
MODIFY COLUMN user_id INT NOT NULL,
MODIFY COLUMN title VARCHAR(255) NOT NULL,
MODIFY COLUMN content TEXT,
MODIFY COLUMN mood VARCHAR(50),
MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD INDEX idx_user_diary (user_id),
ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; 